apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monorepo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: monorepo-api
  app.kubernetes.io/part-of: monorepo
